package dashboardAdmin.manageRooms;

import config.session;
import java.sql.*;
import javax.swing.*;

public class addrooms extends javax.swing.JFrame {

    public addrooms() {
        
        session sess = session.getInstance();

    // 1. Security Check FIRST
    if (sess.getAccountId() == 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Required to Log in!");
        main.login loginForm = new main.login();
        loginForm.setVisible(true);
        this.dispose(); 
        return; 
    }
        initComponents();
        comboRoomStat.setModel(new DefaultComboBoxModel<>(new String[] { "Available", "Occupied", "Maintenance" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addrooms = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        roomid = new javax.swing.JTextField();
        floor = new javax.swing.JTextField();
        roompr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        comboRoomTypeName = new javax.swing.JComboBox<>();
        comboRoomStat = new javax.swing.JComboBox<>();
        roomnum1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addrooms.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        addrooms.setText("ROOMS");
        jPanel1.add(addrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Room Number:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Room Type Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Floor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        status.setText("Status:");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Room ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Room Price:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Description:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("SAVE");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 60, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 40, 20));

        roomid.setEditable(false);
        roomid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomidActionPerformed(evt);
            }
        });
        jPanel1.add(roomid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 140, 30));
        jPanel1.add(floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 140, 30));
        jPanel1.add(roompr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 140, 30));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 140, 110));

        comboRoomTypeName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRoomTypeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboRoomTypeNameMouseClicked(evt);
            }
        });
        jPanel1.add(comboRoomTypeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, 30));

        comboRoomStat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRoomStat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboRoomStatMouseClicked(evt);
            }
        });
        comboRoomStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoomStatActionPerformed(evt);
            }
        });
        jPanel1.add(comboRoomStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 140, 30));
        jPanel1.add(roomnum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Object selected = comboRoomTypeName.getSelectedItem();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a Room Type!");
            return;
        }
        
        String selectedItem = selected.toString();
        int rTypeID = Integer.parseInt(selectedItem.split(" - ")[0]);
        String rStatus = comboRoomStat.getSelectedItem().toString();

        try (Connection conn = DriverManager.getConnection("jdbc:sqlite:booking.db")) {
            String sql = "INSERT INTO rooms(room_number, room_type_id, floor, room_price, status, description) VALUES(?,?,?,?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setString(1, roomnum1.getText()); // Use roomnum1 based on your variables
            pstmt.setInt(2, rTypeID);
            pstmt.setString(3, floor.getText());
            pstmt.setDouble(4, Double.parseDouble(roompr.getText()));
            pstmt.setString(5, rStatus); 
            pstmt.setString(6, desc.getText()); 

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Room Added Successfully!");

            // Redirect and Refresh
            managerooms manage = new managerooms();
            manage.setVisible(true); 
            this.dispose();          
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    

    
    

    }//GEN-LAST:event_jLabel9MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        managerooms manage = new managerooms();
        manage.setVisible(true); // Show the dashboard again
        this.dispose();        // Close the current manageusers window
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited

        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setForeground(java.awt.Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseExited

    private void roomidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomidActionPerformed

    private void comboRoomTypeNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboRoomTypeNameMouseClicked
        try {
            Connection conn = DriverManager.getConnection("jdbc:sqlite:booking.db");
            String sql = "SELECT room_type_id, type_name FROM room_type"; 
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();

            comboRoomTypeName.removeAllItems();
            while (rs.next()) {
                comboRoomTypeName.addItem(rs.getInt("room_type_id") + " - " + rs.getString("type_name"));
            }
            conn.close();
        } catch (Exception e) {
            System.out.println("Error populating combo: " + e.getMessage());
        }
    

    }//GEN-LAST:event_comboRoomTypeNameMouseClicked

    private void comboRoomStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoomStatActionPerformed
 
    }//GEN-LAST:event_comboRoomStatActionPerformed

    private void comboRoomStatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboRoomStatMouseClicked
    // 1. Get the type name you just picked
        Object selected = comboRoomTypeName.getSelectedItem();
        if (selected == null) return;
        
        // Get only the Type Name (the part after the " - ")
        String selectedType = selected.toString().split(" - ")[1];

        try (Connection conn = DriverManager.getConnection("jdbc:sqlite:booking.db")) {
            String sql = "SELECT status FROM room_type WHERE type_name = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, selectedType);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                String typeStatus = rs.getString("status");

                if ("Inactive".equalsIgnoreCase(typeStatus)) {
                    comboRoomStat.setSelectedItem("Maintenance");
                    comboRoomStat.setEnabled(false); 
                    JOptionPane.showMessageDialog(this, "Note: This category is currently Inactive.");
                } else {
                    comboRoomStat.setEnabled(true);
                }
            }
        } catch (Exception e) {
            System.out.println("Sync Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_comboRoomStatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addrooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addrooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addrooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addrooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addrooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrooms;
    private javax.swing.JLabel back;
    private javax.swing.JComboBox<String> comboRoomStat;
    private javax.swing.JComboBox<String> comboRoomTypeName;
    private javax.swing.JTextArea desc;
    private javax.swing.JTextField floor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField roomid;
    private javax.swing.JTextField roomnum1;
    private javax.swing.JTextField roompr;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
