/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardAdmin;

import config.config;
import config.session;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Personal-PC
 */
public class manageaccount extends javax.swing.JFrame {

    /**
     * Creates new form manageaccount
     */
    public manageaccount() {
    session sess = session.getInstance();// or public dashboarduser()
    // 1. Security Check FIRST
    if (sess.getAccountId() == 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please Login First!");
        new main.login().setVisible(true);
        this.dispose();
        return;
    }
    
    initComponents();
    displayData(); 
  
}
    
public void displayData() {
    try {
        config conf = new config();
        
        // Removed first_name and last_name from the SELECT statement
        String sql = "SELECT account_id AS 'ID', email AS 'Email', "
                   + "contact AS 'Contact', username AS 'Username', "
                   + "role AS 'Role', account_status AS 'Status' "
                   + "FROM accounts";

        java.sql.ResultSet rs = conf.getData(sql);
        
        // The table will now only show ID, Email, Contact, Username, Role, and Status
        accounts_table.setModel(DbUtils.resultSetToTableModel(rs));
        
        rs.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error fetching data: " + e.getMessage());
    }
}

public void displayData(String sql) {
    try {
        config conf = new config();
        // Use the 'sql' variable passed as an argument, NOT a new hardcoded string
        java.sql.ResultSet rs = conf.getData(sql); 
        accounts_table.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accounts_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        search = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MANAGE ACCOUNTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 650, 100));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 100));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setText("Add");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        jPanel11.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 20));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, 40));

        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Edit ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        edit.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        accounts_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(accounts_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 930, 400));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Delete");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 70, 40));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setText("Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jPanel5.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 120, 100, 30));

        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });
        search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_fieldKeyTyped(evt);
            }
        });
        jPanel1.add(search_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dashboardadmin dash = new dashboardadmin();
        dash.setVisible(true); // Show the dashboard again
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_backMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        add ad = new add();
        ad.setVisible(true); // Show the dashboard again
        this.dispose();
    }//GEN-LAST:event_addMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       int rowIndex = accounts_table.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item to edit!");
        } else {
            try {
                config conf = new config();
                TableModel model = accounts_table.getModel();
                
                // 1. Get the ID from the selected row (Column 0)
                String id = model.getValueAt(rowIndex, 0).toString();
                
                // 2. Query the database to get full details for that ID
                java.sql.ResultSet rs = conf.getData("SELECT * FROM accounts WHERE account_id = '" + id + "'");
                
                if(rs.next()) {
                    edit ed = new edit(); 
                    
                    // --- IMPLEMENTED LOGIC START ---
                    int roleId = rs.getInt("role");
                    if (roleId == 0) {
                        ed.role.setText("Guest");
                    } else if (roleId == 1) {
                        ed.role.setText("Admin");
                    } else {
                        ed.role.setText("Staff");
                    }
                    // --- IMPLEMENTED LOGIC END ---

                    // Pass the rest of the data to the edit form fields
                    ed.fname.setText(rs.getString("first_name"));
                    ed.lname.setText(rs.getString("last_name"));
                    ed.email.setText(rs.getString("email"));
                    ed.contact.setText(rs.getString("contact"));
                    ed.user.setText(rs.getString("username"));
                    ed.pass.setText(""); // Keep password blank for security
                    
                    ed.setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }
    
    }//GEN-LAST:event_jLabel4MouseClicked

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void search_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_fieldKeyTyped
    // Use the current text plus the character currently being typed
    String query = search_field.getText() + evt.getKeyChar();
    
    // Check if the query is practically empty (handling backspaces/empty input)
    if (query.trim().isEmpty()) {
        displayData(); 
        return;
    }

    String sql = "SELECT account_id AS 'ID', email AS 'Email', "
               + "contact AS 'Contact', username AS 'Username', "
               + "role AS 'Role', account_status AS 'Status' "
               + "FROM accounts WHERE "
               + "account_id LIKE '%" + query + "%' OR "
               + "contact LIKE '%" + query + "%' OR "
               + "username LIKE '%" + query + "%' OR "
               + "email LIKE '%" + query + "%' OR "
               + "role LIKE '%" + query + "%'";
               
    displayData(sql); 
    }//GEN-LAST:event_search_fieldKeyTyped

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
    String query = search_field.getText().trim();
    
    if(query.isEmpty()){
        displayData(); 
    } else {
        String sql = "SELECT account_id AS 'ID', email AS 'Email', "
                   + "contact AS 'Contact', username AS 'Username', "
                   + "role AS 'Role', account_status AS 'Status' "
                   + "FROM accounts WHERE "
                   + "account_id LIKE '%" + query + "%' OR "
                   + "contact LIKE '%" + query + "%' OR "
                   + "username LIKE '%" + query + "%' OR "
                   + "role LIKE '%" + query + "%' OR "
                   + "email LIKE '%" + query + "%'";
        displayData(sql);
    }
      // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int rowIndex = accounts_table.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item to delete!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this guest?", "Warning", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    TableModel model = accounts_table.getModel();
                    String id = model.getValueAt(rowIndex, 0).toString();
                    
                    config conf = new config();
                    // Note: Ensure your config.java has the deleteData method
                    int result = conf.deleteData("DELETE FROM accounts WHERE account_id = '" + id + "'");
                    
                    if(result == 1){
                        JOptionPane.showMessageDialog(null, "Deleted Successfully!");
                        displayData(); // Refresh the table
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error deleting: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageaccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accounts_table;
    private javax.swing.JLabel add;
    private javax.swing.JLabel back;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel search;
    private javax.swing.JTextField search_field;
    // End of variables declaration//GEN-END:variables
}
