package dashboardAdmin;

import config.session;
import config.config;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


public class manageguest extends javax.swing.JFrame {

    public manageguest() {
    session sess = session.getInstance();// or public dashboarduser()
    // 1. Security Check FIRST
    if (sess.getAccountId() == 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please Login First!");
        new main.login().setVisible(true);
        this.dispose();
        return;
    }
    
    initComponents();
    displayData(); 
  
}
    
public void displayData() {
    try {
        config conf = new config();
        // Explicitly select only the columns you want to display
        String sql = "SELECT guest_id, first_name, last_name, email, contact, username, status FROM guest";
        java.sql.ResultSet rs = conf.getData(sql);
        guest_table.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch (Exception e) {
        System.out.println("Error Displaying Data: " + e.getMessage());
    }
}
public void displayData(String sql) {
        try {
            config conf = new config();
            java.sql.ResultSet rs = conf.getData(sql);
            guest_table.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        } catch (Exception e) {
            System.out.println("Error Displaying Data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        search_user = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edits = new javax.swing.JPanel();
        edit = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        Table = new javax.swing.JLabel();
        guest_pane = new javax.swing.JScrollPane();
        guest_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setText("Add");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        jPanel11.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 40));

        search_user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("SEARCH");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        search_user.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(search_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 140, 30));

        edits.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit.setText("Edit ");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edits.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jPanel1.add(edits, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 70, 40));

        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Delete");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        delete.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 20));

        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 70, 40));

        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });
        search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_fieldKeyTyped(evt);
            }
        });
        jPanel1.add(search_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 210, 30));

        Table.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Table.setText("USER TABLE");
        jPanel1.add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 20));

        guest_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guest_paneMouseClicked(evt);
            }
        });

        guest_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        guest_pane.setViewportView(guest_table);

        jPanel1.add(guest_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 930, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void guest_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guest_paneMouseClicked
                          // TODO add your handling code here:
    }//GEN-LAST:event_guest_paneMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // Search Button Logic
        String txt = search_field.getText();
        String sql = "SELECT guest_id AS 'ID', username AS 'User', email AS 'Email', contact AS 'Contact', status AS 'Status' "
                   + "FROM guest WHERE username LIKE '%" + txt + "%' OR email LIKE '%" + txt + "%'";
        displayData(sql);



    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int rowIndex = guest_table.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item to delete!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this guest?", "Warning", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    TableModel model = guest_table.getModel();
                    String id = model.getValueAt(rowIndex, 0).toString();
                    
                    config conf = new config();
                    // Note: Ensure your config.java has the deleteData method
                    int result = conf.deleteData("DELETE FROM guest WHERE guest_id = '" + id + "'");
                    
                    if(result == 1){
                        JOptionPane.showMessageDialog(null, "Deleted Successfully!");
                        displayData(); // Refresh the table
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error deleting: " + e.getMessage());
                }
            }
        }
     
    }//GEN-LAST:event_jLabel5MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
    // 1. Create an instance of the add.java class
    add addUserForm = new add();
    
    // 2. Make the add form visible
    addUserForm.setVisible(true);
    
    // 3. Close (dispose) the current usertable window
    this.dispose();

    }//GEN-LAST:event_addMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
    int rowIndex = guest_table.getSelectedRow();

    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(null, "Please select an item to edit!");
    } else {
        try {
            config conf = new config();
            TableModel model = guest_table.getModel();
            
            // 1. Get the ID from the selected row (Column 0)
            String id = model.getValueAt(rowIndex, 0).toString();
            
            // 2. Query the database to get full details for that ID
            java.sql.ResultSet rs = conf.getData("SELECT * FROM guest WHERE guest_id = '" + id + "'");
            
            if(rs.next()) {
                edit ed = new edit(); 
                
                // 3. Pass data to the edit form text fields
                ed.guest_id.setText("" + rs.getInt("guest_id"));
                ed.fname.setText(rs.getString("first_name"));
                ed.lname.setText(rs.getString("last_name"));
                ed.email.setText(rs.getString("email"));
                ed.contact.setText(rs.getString("contact"));
                ed.user.setText(rs.getString("username"));
                ed.pass.setText(""); // Keep password blank for security
                
                ed.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_editMouseClicked

    private void search_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_fieldKeyTyped
    String query = search_field.getText();
    
    // Select specific columns, but search across all relevant fields
    String sql = "SELECT guest_id, first_name, last_name, email, contact, username, status FROM guest WHERE "
               + "first_name LIKE '%" + query + "%' OR "
               + "last_name LIKE '%" + query + "%' OR "
               + "username LIKE '%" + query + "%' OR "
               + "email LIKE '%" + query + "%'";
               
    displayData(sql); 



    }//GEN-LAST:event_search_fieldKeyTyped

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dashboardadmin dash = new dashboardadmin();
        dash.setVisible(true); // Show the dashboard again
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE); 
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageguest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Table;
    private javax.swing.JLabel add;
    private javax.swing.JLabel back;
    private javax.swing.JPanel delete;
    private javax.swing.JLabel edit;
    private javax.swing.JPanel edits;
    private javax.swing.JScrollPane guest_pane;
    private javax.swing.JTable guest_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField search_field;
    private javax.swing.JPanel search_user;
    // End of variables declaration//GEN-END:variables
}
