/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardUser;

import config.session;
import dashboardUser.RoomItem;
import config.config;
import java.sql.*;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.text.SimpleDateFormat;

public class bookings extends javax.swing.JFrame {

    /**
     * Creates new form bookings
     */
public bookings() {
     session sess = session.getInstance();

    if (sess.getAccountId() == 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Required to Log in!");
        main.login loginForm = new main.login();
        loginForm.setVisible(true);
        this.dispose(); 
        return; 
    }
    initComponents(); // This MUST run first to create the objects
    
    // Set default text to avoid calculation errors on startup
    ppn.setText("0");
    totalnights.setText("0");
    totalcost.setText("0.00");

    loadAvailableRooms(); 
    
    // Add listeners AFTER components are loaded
    checkin.getDateEditor().addPropertyChangeListener(evt -> {
        if ("date".equals(evt.getPropertyName())) calculateTotal();
    });
    checkout.getDateEditor().addPropertyChangeListener(evt -> {
        if ("date".equals(evt.getPropertyName())) calculateTotal();
    });
}

    public void loadAvailableRooms() {
    if (availroom == null) return; // Safety check
    
    try {
        config db = new config();
        String sql = "SELECT r.room_id, r.room_number, rt.type_name, " +
                     "rt.description AS roomtype_description, rt.capacity, " +
                     "r.floor, r.room_price, r.description " +
                     "FROM rooms r " +
                     "JOIN room_type rt ON r.room_type_id = rt.room_type_id " +
                     "WHERE r.status = 'Available'";

        java.sql.ResultSet rs = db.getData(sql);
        availroom.removeAllItems(); 

        while (rs.next()) {
            RoomItem item = new RoomItem(
                rs.getInt("room_id"),
                rs.getString("room_number"),
                rs.getString("type_name"),
                rs.getString("roomtype_description"),
                rs.getInt("capacity"),
                rs.getString("floor"),
                rs.getDouble("room_price"),
                rs.getString("description")
            );
            availroom.addItem(item);
        }
    } catch (Exception e) {
        System.out.println("Error loading rooms: " + e.getMessage());
    }
}

    

    private void calculateTotal() {
    try {
        // Safety check: Don't calculate if dates or price are missing
        if (checkin.getDate() != null && checkout.getDate() != null && !ppn.getText().isEmpty()) {

            java.util.Date d1 = checkin.getDate();
            java.util.Date d2 = checkout.getDate();

            long diff = d2.getTime() - d1.getTime();
            long nights = diff / (24 * 60 * 60 * 1000);

            if (nights < 0) {
                JOptionPane.showMessageDialog(null, "Check-out date cannot be before Check-in date!");
                totalnights.setText("0");
                totalcost.setText("0.00");
            } else {
                totalnights.setText(String.valueOf(nights));

                // Convert price safely
                double price = Double.parseDouble(ppn.getText());
                double total = nights * price;

                totalcost.setText(String.format("%.2f", total));
            }
        }
    } catch (NumberFormatException e) {
        // This handles cases where ppn.getText() is not a valid number yet
        totalcost.setText("0.00");
    } catch (Exception e) {
        e.printStackTrace();
    }
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        ppn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        totalcost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        confirmbook = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        availroom = new javax.swing.JComboBox<>();
        totalnights = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("BOOKINGS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 100));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ppn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppnActionPerformed(evt);
            }
        });
        jPanel9.add(ppn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 170, 40));

        jLabel15.setText("Total Cost:");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, -1));

        totalcost.setEditable(false);
        jPanel9.add(totalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 170, 40));

        jLabel12.setText("Check-Out:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        jLabel16.setText("Price Per Night:");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, -1));

        jLabel17.setText("Check-In:");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 20));
        jPanel9.add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, 40));
        jPanel9.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, 40));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        jPanel11.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 80, 30));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmbook.setForeground(new java.awt.Color(255, 255, 255));
        confirmbook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmbook.setText("Confirm Booking");
        confirmbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmbookMouseClicked(evt);
            }
        });
        jPanel12.add(confirmbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 120, 40));

        jLabel2.setText("Available Rooms:");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        availroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availroomMouseClicked(evt);
            }
        });
        availroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availroomActionPerformed(evt);
            }
        });
        jPanel9.add(availroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 380, 50));

        totalnights.setEditable(false);
        jPanel9.add(totalnights, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, 40));

        jLabel18.setText("Total Nights:");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 490, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmbookMouseClicked
    try {
        session sess = session.getInstance();
        int accId = sess.getAccountId(); // Using AccountId as your unique identifier

        RoomItem selected = (RoomItem) availroom.getSelectedItem();
        if (selected == null || checkin.getDate() == null || checkout.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please complete all fields!");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strIn = sdf.format(checkin.getDate());
        String strOut = sdf.format(checkout.getDate());

        config db = new config();

        // ✅ 1. INSERT using your actual DB column names (account_id, total_night)
        String sql = "INSERT INTO bookings (account_id, room_id, check_in, check_out, total_night, total_price, booking_status) "
                   + "VALUES (?, ?, ?, ?, ?, ?, 'Booked')";

        int result = db.executeUpdate(sql, 
            accId, 
            selected.getroomId(), 
            strIn, 
            strOut, 
            Integer.parseInt(totalnights.getText()), 
            Double.parseDouble(totalcost.getText())
        );

        if (result > 0) {
            // ✅ 2. Update Room Status so it "vanishes" from the available list
            String updateRoom = "UPDATE rooms SET status='Occupied' WHERE room_id=?";
            db.executeUpdate(updateRoom, selected.getroomId());

            JOptionPane.showMessageDialog(null, "Booking Successful! ✅");

            // ✅ 3. Refresh and Close
            new mybookings().setVisible(true); // Open the table view
            this.dispose(); // Close current booking window
        }

    } catch (Exception e) {
        System.out.println("Booking Error: " + e.getMessage());
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_confirmbookMouseClicked

    private void ppnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppnActionPerformed

    private void availroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availroomActionPerformed
    RoomItem selected = (RoomItem) availroom.getSelectedItem();

    if (selected != null) {
        ppn.setText(String.valueOf(selected.getPrice()));
        calculateTotal(); // 👈 Add this line here!
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_availroomActionPerformed

    private void availroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availroomMouseClicked
    
    RoomItem selected = (RoomItem) availroom.getSelectedItem();

    if (selected != null) {
        ppn.setText(String.valueOf(selected.getPrice()));
    }
    }//GEN-LAST:event_availroomMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        dashboardguest dash = new dashboardguest();
        dash.setVisible(true); // Show the dashboard again
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<dashboardUser.RoomItem> availroom;
    private javax.swing.JLabel cancel;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JLabel confirmbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField ppn;
    private javax.swing.JTextField totalcost;
    private javax.swing.JTextField totalnights;
    // End of variables declaration//GEN-END:variables
}
