/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardUser;

import config.config;

/**
 *
 * @author Personal-PC
 */
public class editbookings extends javax.swing.JFrame {
// Top of editbookings class
public int bookingId = -1;      
public int selectedRoomId = -1; 
public double roomPrice = 0.0;  



// Updated Constructor
public editbookings(int bId, String roomName, String cin, String cout, int nights, double cost) {
    initComponents();
    this.bookingId = bId;
    this.ar.setText(roomName);
    this.totalnights.setText(String.valueOf(nights));
    this.totalcost.setText(String.valueOf(cost));
    
    if (nights > 0) {
        this.roomPrice = cost / nights;
    }

    // ADD THESE SO IT WORKS WHEN OPENED FROM MYBOOKINGS
    checkin.addPropertyChangeListener(evt -> {
        if ("date".equals(evt.getPropertyName())) calculateTotal();
    });
    checkout.addPropertyChangeListener(evt -> {
        if ("date".equals(evt.getPropertyName())) calculateTotal();
    });
}

// Add this helper method so MyBookings can set the dates
public void setDates(java.util.Date in, java.util.Date out) {
    this.checkin.setDate(in);
    this.checkout.setDate(out);
    calculateTotal(); // Trigger calculation immediately after setting initial dates
}
    public editbookings() {
        initComponents();
 }
    
    
public void calculateTotal() {
    if (checkin.getDate() != null && checkout.getDate() != null) {
        // Calculate the difference in milliseconds
        long diff = checkout.getDate().getTime() - checkin.getDate().getTime();
        
        // Convert milliseconds to days (1000ms * 60s * 60m * 24h)
        long days = diff / (24 * 60 * 60 * 1000);

        if (days < 0) {
            // If user picks a checkout date BEFORE checkin
            totalnights.setText("0");
            totalcost.setText("0.00");
        } else {
            // Use 1 as minimum nights if dates are the same
            if (days == 0) days = 1; 

            totalnights.setText(String.valueOf(days));
            
            // roomPrice was calculated in your constructor
            double total = days * roomPrice; 
            totalcost.setText(String.format("%.2f", total));
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        totalcost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        cancelbooking = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalnights = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ar = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        editbooking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDIT BOOKINGS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 430, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 100));

        jPanel9.setBackground(new java.awt.Color(102, 204, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Total Cost:");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, -1));

        totalcost.setEditable(false);
        jPanel9.add(totalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 40));

        jLabel12.setText("Check-Out:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        jLabel17.setText("Check-In:");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 20));

        checkin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                checkinPropertyChange(evt);
            }
        });
        jPanel9.add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, 40));

        checkout.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                checkoutPropertyChange(evt);
            }
        });
        jPanel9.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, 40));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        jPanel11.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 110, 40));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelbooking.setForeground(new java.awt.Color(255, 255, 255));
        cancelbooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelbooking.setText("Cancel  Booking");
        cancelbooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbookingMouseClicked(evt);
            }
        });
        jPanel12.add(cancelbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 40));

        jLabel2.setText("Available Rooms:");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        totalnights.setEditable(false);
        jPanel9.add(totalnights, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, 40));

        jLabel18.setText("Total Nights:");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 20));

        ar.setEditable(false);
        ar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arMouseClicked(evt);
            }
        });
        jPanel9.add(ar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 310, 40));

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editbooking.setForeground(new java.awt.Color(255, 255, 255));
        editbooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editbooking.setText("Update Booking");
        editbooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbookingMouseClicked(evt);
            }
        });
        jPanel13.add(editbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 120, 40));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        mybookings book = new mybookings();
        book.setVisible(true); // Show the dashboard again
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void cancelbookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbookingMouseClicked
    // 1. Confirm with the user before proceeding
    int confirm = javax.swing.JOptionPane.showConfirmDialog(null, 
            "Are you sure you want to cancel this booking?", "Confirm Cancellation", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            config db = new config();
            
            // 2. Update the status in the database using the hidden bookingId
            String sql = "UPDATE bookings SET booking_status = 'Cancelled' WHERE bookings_id = ?";
            
            int result = db.executeUpdate(sql, bookingId);

            if (result > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Booking has been Cancelled successfully.");
                
                // 3. Refresh and return to the bookings list
                mybookings mb = new mybookings();
                mb.setVisible(true);
                this.dispose(); 
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Cancellation Error: " + e.getMessage());
        }
    }


    }//GEN-LAST:event_cancelbookingMouseClicked

    private void arMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arMouseClicked
 
    }//GEN-LAST:event_arMouseClicked

    private void checkinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkinPropertyChange
     if ("date".equals(evt.getPropertyName())) {
        calculateTotal();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_checkinPropertyChange

    private void checkoutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkoutPropertyChange
      if ("date".equals(evt.getPropertyName())) {
        calculateTotal();
    }  // TODO add your handling code here:
    }//GEN-LAST:event_checkoutPropertyChange

    private void editbookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbookingMouseClicked
try {
        config db = new config();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String strIn = sdf.format(checkin.getDate());
        String strOut = sdf.format(checkout.getDate());

        // Use UPDATE instead of INSERT
        String sql = "UPDATE bookings SET check_in = ?, check_out = ?, total_night = ?, total_price = ? "
                   + "WHERE bookings_id = ?";

        int result = db.executeUpdate(sql, 
            strIn, 
            strOut, 
            Integer.parseInt(totalnights.getText()), 
            Double.parseDouble(totalcost.getText()), 
            bookingId
        );

        if (result > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Booking Updated Successfully!");
            new mybookings().setVisible(true);
            this.dispose();
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Update Error: " + e.getMessage());
    }
          }//GEN-LAST:event_editbookingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editbookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editbookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editbookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editbookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editbookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ar;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel cancelbooking;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JLabel editbooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JTextField totalcost;
    public javax.swing.JTextField totalnights;
    // End of variables declaration//GEN-END:variables
}
