package dashboardUser;

import config.config;
import config.session;
import javax.swing.JOptionPane;
import java.sql.*;

public class payments extends javax.swing.JFrame {

    // Instantiate config once to use its methods
    config conf = new config();

    public payments() {
        session sess = session.getInstance();

        if (sess.getAccountId() == 0) {
            JOptionPane.showMessageDialog(null, "Required to Log in!");
            new main.login().setVisible(true);
            this.dispose(); 
            return; 
        }
        
        initComponents();
        loadBookingIDs();
        loadPaymentMethods();
        
        // Make summary fields read-only so users can't change the price
        roomNo.setEditable(false);
        checkin.setEditable(false);
        checkout.setEditable(false);
        totaln.setEditable(false);
        ppn.setEditable(false);
        totalamount.setEditable(false);
    }
    
    private void loadPaymentMethods() {
        paymentmethods.removeAllItems();
        paymentmethods.addItem("Cash");
        paymentmethods.addItem("GCash");
        paymentmethods.addItem("PayMaya");
        paymentmethods.addItem("Credit Card");
    }

    private void processPayment(String bookingId, String method, String amountPaid) {
    // FIX: Changed 'booking_id' to 'bookings_id' to match your payments table screenshot
    String insertPayment = "INSERT INTO payments (bookings_id, amount, payment_method, payment_status, payment_date) "
                         + "VALUES (?, ?, ?, ?, datetime('now'))";
        String updateBooking = "UPDATE bookings SET booking_status = 'Paid' WHERE bookings_id = ?";

    try (Connection con = conf.connectDB()) {
        con.setAutoCommit(false); // Transactions keep your data safe

        // This line (ps1) was causing your error because of the name mismatch
        try (PreparedStatement ps1 = con.prepareStatement(insertPayment)) {
            ps1.setString(1, bookingId);
            ps1.setString(2, amountPaid);
            ps1.setString(3, method);
            ps1.setString(4, "Paid"); 
            ps1.executeUpdate();
        }

        try (PreparedStatement ps2 = con.prepareStatement(updateBooking)) {
            ps2.setString(1, bookingId);
            ps2.executeUpdate();
        }

        con.commit(); 
        JOptionPane.showMessageDialog(this, "Payment Successful!");

        new dashboardguest().setVisible(true);
        this.dispose(); 

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Payment Failed! Error: " + e.getMessage());
    }
}
    
    private void loadBookingIDs() {
    session sess = session.getInstance();
    int currentUserId = sess.getAccountId();

    // Changed 'booking_id' to 'bookings_id' to match your bookings table schema
    String sql = "SELECT bookings_id FROM bookings WHERE account_id = ? AND booking_status != 'Paid'";
    
    try (Connection con = conf.connectDB();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setInt(1, currentUserId);
        ResultSet rs = ps.executeQuery();

        bookingID.removeAllItems();
        while (rs.next()) {
            // Updated to get 'bookings_id'
            bookingID.addItem(rs.getString("bookings_id"));
        }

    } catch (Exception e) {
        e.printStackTrace(); 
        JOptionPane.showMessageDialog(this, "Error loading IDs: " + e.getMessage());
    }
}

    private void loadBookingDetails(String bookingId) {
    // Corrected column names: bookings_id and total_night
    String sql = "SELECT bookings_id, check_in, check_out, total_night, total_price, room_id " +
                 "FROM bookings WHERE bookings_id = ?";

    try (Connection con = conf.connectDB();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, bookingId);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                roomNo.setText(rs.getString("room_id"));
                checkin.setText(rs.getString("check_in"));
                checkout.setText(rs.getString("check_out"));
                totaln.setText(rs.getString("total_night")); // Corrected singular name
                
                String price = rs.getString("total_price");
                ppn.setText(price);
                totalamount.setText(price);
                amount.setText(price); 
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading details: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        paymentmethods = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        confirmbook = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        cancel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        roomNo = new javax.swing.JTextField();
        ppn = new javax.swing.JTextField();
        totaln = new javax.swing.JTextField();
        checkout = new javax.swing.JTextField();
        checkin = new javax.swing.JTextField();
        totalamount = new javax.swing.JTextField();
        bookingID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("PAYMENTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total Amount:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, -1));

        jLabel3.setText("Booking ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, -1));

        jLabel4.setText("RoomNumber:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, -1));

        jLabel6.setText("Check-In:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, -1));

        jLabel7.setText("Check-Out:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, -1));

        jLabel8.setText("Total Nights:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, -1));

        jLabel9.setText("PricePerNights:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BOOKING SUMMARY");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, 40));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Amount:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, -1));

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel4.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, 40));

        jLabel11.setText("PAYMENT METHODS:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 30));

        jPanel4.add(paymentmethods, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 190, 40));

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmbook.setForeground(new java.awt.Color(255, 255, 255));
        confirmbook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmbook.setText("Confirm Booking");
        confirmbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmbookMouseClicked(evt);
            }
        });
        jPanel13.add(confirmbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, 40));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel1.setForeground(new java.awt.Color(255, 255, 255));
        cancel1.setText("Cancel");
        cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel1MouseExited(evt);
            }
        });
        jPanel12.add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 20));

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 80, 30));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        jPanel11.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 300, 310));
        jPanel1.add(roomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 120, -1));
        jPanel1.add(ppn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 130, -1));
        jPanel1.add(totaln, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 120, -1));
        jPanel1.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 140, -1));
        jPanel1.add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 140, -1));
        jPanel1.add(totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 120, -1));

        bookingID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingIDActionPerformed(evt);
            }
        });
        jPanel1.add(bookingID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        dashboardguest dash = new dashboardguest();
        dash.setVisible(true); // Show the dashboard again
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void cancel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1MouseClicked
        dashboardguest dash = new dashboardguest();
        dash.setVisible(true); // Show the dashboard again
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_cancel1MouseClicked

    private void cancel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1MouseEntered
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancel1MouseEntered

    private void cancel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1MouseExited
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancel1MouseExited

    private void confirmbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmbookMouseClicked
    if (bookingID.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Select a booking first!");
        return;
    }

    // Safety check: Make sure amount isn't empty
    if (amount.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an amount!");
        return;
    }

    String bookingId = bookingID.getSelectedItem().toString();
    String method = paymentmethods.getSelectedItem().toString();
    String amountPaid = amount.getText();

    // Call the fixed processPayment method below
    processPayment(bookingId, method, amountPaid);

   // TODO add your handling code here:
    }//GEN-LAST:event_confirmbookMouseClicked

    private void bookingIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingIDActionPerformed

    if (bookingID.getSelectedItem() == null) return;

    String id = bookingID.getSelectedItem().toString();

    loadBookingDetails(id);
  // TODO add your handling code here:
    }//GEN-LAST:event_bookingIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox<String> bookingID;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel cancel1;
    private javax.swing.JTextField checkin;
    private javax.swing.JTextField checkout;
    private javax.swing.JLabel confirmbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> paymentmethods;
    private javax.swing.JTextField ppn;
    private javax.swing.JTextField roomNo;
    private javax.swing.JTextField totalamount;
    private javax.swing.JTextField totaln;
    // End of variables declaration//GEN-END:variables
}
