/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardUser;

import javax.swing.table.DefaultTableModel;
import config.session;
import config.config;
import java.sql.*;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.text.SimpleDateFormat;

public class payments extends javax.swing.JFrame {

  String currentBookingID;
  int currentAccountID;

   public payments(int accID) {
    initComponents();
    this.currentAccountID = accID;
}

public void importBookingData(String bID, String rNo, String cin, String cout, String nights, String price, String tableInfo) {
    this.currentBookingID = bID; // Saves the ID for the SQL update later
    paymentstable.setText(tableInfo); 
    rooms.setText(rNo);
    tn.setText(nights);
    tc.setText(price);
    jTextField1.setText(price); // Sets the Amount field automatically
    
    // Auto-fill the Date Choosers
    try {
        java.util.Date dateIn = new SimpleDateFormat("yyyy-MM-dd").parse(cin);
        java.util.Date dateOut = new SimpleDateFormat("yyyy-MM-dd").parse(cout);
        checkin.setDate(dateIn);
        checkout.setDate(dateOut);
    } catch (Exception e) {
        System.err.println("Date Error: " + e.getMessage());
    }
    
    setupPaymentMethods(); // Populates Cash, GCash, etc.
}

private void setupPaymentMethods() {
        pm.removeAllItems();
        pm.addItem("Cash");
        pm.addItem("GCash");
        pm.addItem("Credit Card");
        pm.addItem("PayPal");
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        rooms = new javax.swing.JTextField();
        tn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pm = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        paynow = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        paymentstable = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));

        jLabel2.setText("Check-In:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, 30));

        jLabel3.setText("Check-Out:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 30));
        jPanel1.add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 30));
        jPanel1.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 150, 30));

        jLabel4.setText("Total Nights:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 80, 30));

        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        jPanel1.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 150, 30));
        jPanel1.add(rooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, 30));
        jPanel1.add(tn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 150, 30));

        jLabel5.setText("Rooms:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 60, 30));

        jLabel6.setText("Total Cost:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 70, 30));

        jLabel7.setText("Payment Method:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 100, 30));

        pm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmActionPerformed(evt);
            }
        });
        jPanel1.add(pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 150, 30));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paynow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paynow.setForeground(new java.awt.Color(255, 255, 255));
        paynow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paynow.setText("PAY NOW");
        paynow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paynowMouseClicked(evt);
            }
        });
        jPanel12.add(paynow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 120, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 40, 20));

        jLabel8.setText("Amount:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 60, 30));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, 30));

        paymentstable.setEditable(false);
        paymentstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentstableMouseClicked(evt);
            }
        });
        jPanel1.add(paymentstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 340, 50));

        jLabel9.setText("TABLE:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmActionPerformed

    private void paynowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paynowMouseClicked
    if(currentBookingID == null) {
        JOptionPane.showMessageDialog(null, "Please select a booking first!");
        return;
    }
    
    config conf = new config();
    String method = pm.getSelectedItem().toString();
    String amount = jTextField1.getText();
    
    // SQL query structure. Make sure you insert account_id.
    String payQuery = "INSERT INTO payments (account_id, bookings_id, amount, payment_method, payment_status, payment_date) "
                    + "VALUES (?, ?, ?, ?, 'Pending', datetime('now'))";
    
    // SQL update for booking status
    String updateQuery = "UPDATE bookings SET booking_status = 'Pending' WHERE bookings_id = ?";
    
    // Pass 'currentAccountID' as the FIRST parameter to 'execute'
    if(conf.executeUpdate(payQuery, currentAccountID, currentBookingID, amount, method) > 0) {
        conf.executeUpdate(updateQuery, currentBookingID);
        JOptionPane.showMessageDialog(null, "Payment Submitted! Status: Pending Staff Approval.");
        
        this.dispose();
        new mybookings().setVisible(true); 
    }
   
    }//GEN-LAST:event_paynowMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dashboardguest dash = new dashboardguest();
    dash.setVisible(true); 
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_backMouseExited

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    private void paymentstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentstableMouseClicked
     mybookings mybook = new mybookings();       // TODO add your handling code here:
     mybook.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_paymentstableMouseClicked

    /**
     * @param args the command line arguments
     */
         public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Change 'new payments()' to 'new payments(0)'
            new payments(0).setVisible(true); 
        }
    });
}
    
       
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField paymentstable;
    private javax.swing.JLabel paynow;
    private javax.swing.JComboBox<String> pm;
    private javax.swing.JTextField rooms;
    private javax.swing.JTextField tc;
    private javax.swing.JTextField tn;
    // End of variables declaration//GEN-END:variables
}
