/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardUser.guestprofileEdit;

import javax.swing.JOptionPane;
import config.session;
import config.config;
import config.passwordhashed;


public class editguestprofile extends javax.swing.JFrame {

    /**
     * Creates new form editguestprofile
     */
    public editguestprofile() {
    initComponents();
    displayData(); // Add this line to load the info
}

public void displayData() {
    session sess = session.getInstance();
    // Use the specific Guest ID for the guest table
    accts_id.setText("" + sess.getAccountId()); 
    edit_fname.setText(sess.getFname());
    edit_lname.setText(sess.getLname());
    edit_email.setText(sess.getEmail());
    edit_contact.setText(sess.getContact());
    edit_user.setText(sess.getUsername());
    edit_pass.setText(sess.getPass());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        USERID = new javax.swing.JLabel();
        accts_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edit_pass = new javax.swing.JTextField();
        edit_lname = new javax.swing.JTextField();
        edit_email = new javax.swing.JTextField();
        edit_contact = new javax.swing.JTextField();
        edit_user = new javax.swing.JTextField();
        edit_fname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("DASHBOARD");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 270, 100));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 100));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        USERID.setText("GUEST ID:");

        accts_id.setEditable(false);
        accts_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accts_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(USERID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accts_id, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(USERID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accts_id, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("EDIT GUEST PROFILE");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 310, -1));

        jLabel2.setText("Password:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel3.setText("First Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel5.setText("Email:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel6.setText("Contact:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel8.setText("Username:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));
        jPanel2.add(edit_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 150, 30));

        edit_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_lnameActionPerformed(evt);
            }
        });
        jPanel2.add(edit_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, 30));
        jPanel2.add(edit_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 150, 30));
        jPanel2.add(edit_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 150, 30));
        jPanel2.add(edit_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 150, 30));

        edit_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_fnameActionPerformed(evt);
            }
        });
        jPanel2.add(edit_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 150, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel4.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 20));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("UPDATE");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accts_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accts_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accts_idActionPerformed

    private void edit_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_lnameActionPerformed

    private void edit_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_fnameActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dashboardUser.guestprofileEdit.guestprofile dash = new dashboardUser.guestprofileEdit.guestprofile();
        dash.setVisible(true); // Show the dashboard again
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_backMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    session sess = session.getInstance(); //
    config db = new config();

    // 1. Fetch data from the UI components
    // Ensure these names match the "Variable Name" in the Design tab exactly
    String firstName = edit_fname.getText(); 
    String lastName  = edit_lname.getText();
    String userEmail = edit_email.getText();
    String userCont  = edit_contact.getText();
    String userUname = edit_user.getText();
    String rawPass = edit_pass.getText();
    try {
        String updateQuery;
        
        // 2. Check for Password Update and use Hashing
        if (!rawPass.isEmpty() && !rawPass.equals("********")) {
            String hashedPass = passwordhashed.hashPassword(rawPass); 
            updateQuery = "UPDATE accounts SET first_name = '" + firstName + "', "
                        + "last_name = '" + lastName + "', email = '" + userEmail + "', "
                        + "contact = '" + userCont + "', username = '" + userUname + "', "
                        + "password = '" + hashedPass + "' "
                        + "WHERE account_id = " + sess.getAccountId();
        } else {
            updateQuery = "UPDATE accounts SET first_name = '" + firstName + "', "
                        + "last_name = '" + lastName + "', email = '" + userEmail + "', "
                        + "contact = '" + userCont + "', username = '" + userUname + "' "
                        + "WHERE account_id = " + sess.getAccountId();
        }

        // 3. Execute and Sync Session
        if (db.executeUpdate(updateQuery) > 0) {
            JOptionPane.showMessageDialog(null, "Guest Profile Updated Successfully!");
            
            // Sync session so changes reflect globally
            sess.setFname(firstName);
            sess.setLname(lastName);
            sess.setEmail(userEmail);
            sess.setContact(userCont);
            sess.setUsername(userUname);
            sess.setPass(rawPass);

            new dashboardUser.guestprofileEdit.guestprofile().setVisible(true);
            this.dispose();
        }
    } catch (Exception e) {
        System.out.println("Update Error: " + e.getMessage());
    }

    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editguestprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editguestprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editguestprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editguestprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editguestprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel USERID;
    private javax.swing.JTextField accts_id;
    private javax.swing.JLabel back;
    private javax.swing.JTextField edit_contact;
    private javax.swing.JTextField edit_email;
    private javax.swing.JTextField edit_fname;
    private javax.swing.JTextField edit_lname;
    private javax.swing.JTextField edit_pass;
    private javax.swing.JTextField edit_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
