/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Personal-PC
 */
public class loan extends javax.swing.JFrame {

    /**
     * Creates new form loan
     */
    public loan() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        load = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loading = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 100, 237, 58);

        jLabel2.setText("Don't Judge the Design by its Cover");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 180, 290, 14);

        load.setBackground(new java.awt.Color(255, 0, 51));
        load.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        load.setForeground(new java.awt.Color(255, 51, 51));
        load.setText("Loading ...");
        jPanel1.add(load);
        load.setBounds(10, 390, 390, 20);

        percent.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 51, 51));
        percent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        percent.setText("0%");
        jPanel1.add(percent);
        percent.setBounds(680, 390, 70, 20);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 790, 420);

        loading.setBackground(new java.awt.Color(255, 51, 51));
        loading.setForeground(new java.awt.Color(255, 51, 51));
        loading.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loading.setPreferredSize(new java.awt.Dimension(146, 10));
        jPanel1.add(loading);
        loading.setBounds(-10, 410, 800, 10);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(710, 0, 50, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    loan lo = new loan();
    lo.setLocationRelativeTo(null); // This centers the window
    lo.setVisible(true);

    try {
        // 1. Run the loop until it hits 100
        for (int i = 0; i <= 100; i++) {
            Thread.sleep(50); // Keep it at 50 for a smooth look
            lo.percent.setText(i + "%");
            lo.loading.setValue(i);

            if (i == 10) lo.load.setText("Turning On Modules. . .");
            if (i == 20) lo.load.setText("Loading Modules. . .");
            if (i == 50) lo.load.setText("Connecting to Database. . .");
            if (i == 70) lo.load.setText("Launching Application. . .");
        }
        
        // 2. Loop is FINISHED. Now handle the hand-off.
        
        // Use 'loginForm' or 'login' depending on which class you want to open
        login log = new login(); 
        log.setVisible(true);
        
        // 3. This WILL kill the loading screen now
        lo.dispose(); 

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }


        
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel load;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel percent;
    // End of variables declaration//GEN-END:variables
}
