/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import config.session;
import dashboardUser.guestprofileEdit.guestprofile; 
import dashboardAdmin.dashboardadmin;
import dashboardUser.dashboardguest;
import config.config;
import config.passwordhashed;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


/**
 *
 * @author Personal-PC
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        loginpass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        loginuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginpassActionPerformed(evt);
            }
        });
        jPanel2.add(loginpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 240, 40));

        jLabel1.setText("Username:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 80, -1));

        jLabel2.setText("Password:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, -1));

        login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOGIN");
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        loginuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginuserActionPerformed(evt);
            }
        });
        jPanel2.add(loginuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("New User?Click here to Register");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 240, 20));

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("LOG IN");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 130, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 0, 440, 454));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginpassActionPerformed

    private void loginuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginuserActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        register reg = new register();
        this.dispose();
        reg.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    String user = loginuser.getText().trim();
    String rawPass = loginpass.getText().trim();

    if(user.isEmpty() || rawPass.isEmpty()){
        JOptionPane.showMessageDialog(null, "Please fill in all fields!");
        return;
    }

    try {
        config db = new config();
        String hashedPass = passwordhashed.hashPassword(rawPass);
        
        // 1. USE PARAMETERS (?) TO PREVENT SQL INJECTION
        String query = "SELECT * FROM accounts WHERE username = ? AND password = ?";
        
        // 2. FETCH DATA (Using our new refactored getData that closes the connection)
        java.sql.ResultSet rs = db.getData(query, user, hashedPass);
        
        if (rs != null && rs.next()) {
            String status = rs.getString("account_status");
            
            if (!status.equalsIgnoreCase("Active")) {
                JOptionPane.showMessageDialog(null, "This account is " + status + ". Please contact support.");
                return;
            }

            // 3. SET SESSION DATA
            session sess = session.getInstance();
            sess.setAccountId(rs.getInt("account_id")); 
            sess.setUsername(rs.getString("username"));
            sess.setRole(rs.getString("role"));
            sess.setStatus(status);
            
            String role = rs.getString("role");
            JOptionPane.showMessageDialog(null, "Login Success! Welcome, " + rs.getString("first_name"));
            
            // 4. REDIRECT BASED ON ROLE
            this.dispose(); // Close login first to free up resources
            
            if (role.equalsIgnoreCase("Admin")) {
                new dashboardAdmin.dashboardadmin().setVisible(true);
            } 
            else if (role.equalsIgnoreCase("Staff")) {
                new dashboardStaff.dashboardstaff().setVisible(true);
            } 
            else if (role.equalsIgnoreCase("Guest")) {
                new dashboardUser.dashboardguest().setVisible(true);
            } 
            else {
                JOptionPane.showMessageDialog(null, "Role '" + role + "' is not recognized.");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
        }
        
        // NO NEED TO MANUALLY CLOSE rs HERE - CachedRowSet handled the DB connection!
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Login Error: " + e.getMessage());
        e.printStackTrace();
    }



    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel login;
    private javax.swing.JTextField loginpass;
    private javax.swing.JTextField loginuser;
    // End of variables declaration//GEN-END:variables
}
