/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardStaff;

import config.session;
import dashboardUser.RoomItem;
import config.config;
import dashboardUser.mybookings;
import java.sql.*;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.text.SimpleDateFormat;

 
public class addbooking extends javax.swing.JFrame {

  public int selectedRoomId = -1; 
    public javax.swing.JTextField ppn;
    
public addbooking() {
    initComponents(); // Always call this first
    
    // 1. Initialize ppn if it's null
    if (ppn == null) {
        ppn = new javax.swing.JTextField();
        ppn.setText("0");
    }

    // 2. Set default values
    totalnights.setText("0");
    totalcost.setText("0.00");
    ar.setEditable(false);

    // 3. Add PropertyChangeListeners to trigger calculation immediately on date selection
    checkin.addPropertyChangeListener("date", new java.beans.PropertyChangeListener() {
        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            calculateTotal();
        }
    });

    checkout.addPropertyChangeListener("date", new java.beans.PropertyChangeListener() {
        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            calculateTotal();
        }
    });
}

public void calculateTotal() {
    try {
        if (checkin.getDate() != null && checkout.getDate() != null && ppn != null && !ppn.getText().isEmpty()) {
            java.util.Date d1 = checkin.getDate();
            java.util.Date d2 = checkout.getDate();

            // Calculate the difference in milliseconds
            long diff = d2.getTime() - d1.getTime();
            
            // Convert to days and ADD 1 to include both start and end days
            long days = (diff / (24 * 60 * 60 * 1000)) + 1;

            if (days <= 0) {
                totalnights.setText("0");
                totalcost.setText("0.00");
            } else {
                totalnights.setText(String.valueOf(days));
                
                // Get price from the ppn field
                double price = Double.parseDouble(ppn.getText());
                double total = days * price;
                
                totalcost.setText(String.format("%.2f", total));
            }
        }
    } catch (Exception e) {
        // Silently handle parsing errors while typing
        totalcost.setText("0.00");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        totalcost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        confirmbook = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalnights = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOKINGS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 100));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Total Cost:");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, 40));

        totalcost.setEditable(false);
        jPanel9.add(totalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, 40));

        jLabel12.setText("Check-Out:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 40));

        jLabel17.setText("Check-In:");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 40));
        jPanel9.add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, 40));
        jPanel9.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 40));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        jPanel11.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, 40));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmbook.setForeground(new java.awt.Color(255, 255, 255));
        confirmbook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmbook.setText("Confirm Booking");
        confirmbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmbookMouseClicked(evt);
            }
        });
        jPanel12.add(confirmbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, 40));

        jLabel2.setText("Available Rooms:");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 40));

        totalnights.setEditable(false);
        jPanel9.add(totalnights, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 40));

        jLabel18.setText("Total Nights:");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 40));

        ar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arMouseClicked(evt);
            }
        });
        jPanel9.add(ar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        dashboardstaff dash = new dashboardstaff();
        dash.setVisible(true); // Show the dashboard again
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void confirmbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmbookMouseClicked
  try {
        session sess = session.getInstance();
        int accId = sess.getAccountId();

        // 1. Validation: This check failed before because selectedRoomId was -1
        if (selectedRoomId == -1) {
            JOptionPane.showMessageDialog(null, "Please select a room from the list first!");
            return;
        }
        if (checkin.getDate() == null || checkout.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please select both Check-In and Check-Out dates!");
            return;
        }

        // 2. Format dates for SQL (YYYY-MM-DD)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strIn = sdf.format(checkin.getDate());
        String strOut = sdf.format(checkout.getDate());

        config db = new config();

        // 3. Insert into bookings table
        // Ensure column names match your database: account_id, room_id, check_in, check_out, total_night, total_price
        String sql = "INSERT INTO bookings (account_id, room_id, check_in, check_out, total_night, total_price, booking_status) "
                   + "VALUES (?, ?, ?, ?, ?, ?, 'Booked')";

        int result = db.executeUpdate(sql, 
            accId, 
            selectedRoomId, 
            strIn, 
            strOut, 
            Integer.parseInt(totalnights.getText()), // This will be '4' for Mar 7-10
            Double.parseDouble(totalcost.getText())  // This will be '2800'
        );

        // 4. Update Room Status to 'Occupied' so it disappears from 'Available' list
        if (result > 0) {
            db.executeUpdate("UPDATE rooms SET status='Occupied' WHERE room_id=?", selectedRoomId);
            
            JOptionPane.showMessageDialog(null, "Booking Successful! ✅\nTotal Days: " + totalnights.getText());
            
            // Redirect to your bookings list
            new mybookings().setVisible(true);
            this.dispose();
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Invalid price or night calculation. Please re-select dates.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Booking Error: " + e.getMessage());
    }
       

    }//GEN-LAST:event_confirmbookMouseClicked

    private void arMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arMouseClicked
    selectavailrooms sar = new selectavailrooms();
    sar.setVisible(true);
    this.dispose(); // Close current window
        // TODO add your handling code here:
    }//GEN-LAST:event_arMouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addbooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ar;
    private javax.swing.JLabel cancel;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JLabel confirmbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JTextField totalcost;
    public javax.swing.JTextField totalnights;
    // End of variables declaration//GEN-END:variables
}
