/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardStaff;

import config.session;
import dashboardStaff.staffprofileEdit.staffprofile;

/**
 *
 * @author Personal-PC
 */
public class dashboardstaff extends javax.swing.JFrame {

    /**
     * Creates new form dashboardStaff
     */
    public dashboardstaff() {
        session sess = session.getInstance();

    if (sess.getAccountId() == 0) {
    javax.swing.JOptionPane.showMessageDialog(null, "Required to Log in!");
        main.login loginForm = new main.login();
        loginForm.setVisible(true);
        this.dispose(); 
        return; 
    }

    // 2. Build the UI only if logged in
    initComponents();
    welcome_staff.setText("Welcome, " + sess.getUsername());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        sd = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        mb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sp = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        pay = new javax.swing.JLabel();
        welcome_staff = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        jPanel8.setBackground(new java.awt.Color(102, 153, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sd.setText("Staff Dashboard");
        jPanel7.add(sd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 40));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mb.setText("Manage Bookings");
        mb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mbMouseClicked(evt);
            }
        });
        jPanel4.add(mb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sp.setText("Staff Profile");
        sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spMouseExited(evt);
            }
        });
        jPanel3.add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanel8.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, 40));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LOG OUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel6.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 40));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pay.setText("Payments");
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        jPanel9.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 460));

        welcome_staff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcome_staff.setText("Welcome, staffname");
        jPanel1.add(welcome_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 200, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("INTRODUCTION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 180, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
       int confirm = javax.swing.JOptionPane.showConfirmDialog(null, 
            "Are you sure you want to logout?", "Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION);
            
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // 2. Clear the Session Singleton
        session sess = session.getInstance();
        sess.setAccountId(0);
        sess.setUsername(null);
        sess.setEmail(null);
        sess.setRole(null);
        sess.setStatus(null);
        
        // 3. Navigate to Login
        main.login loginForm = new main.login();
        loginForm.setVisible(true);
        
        // 4. Close the current dashboard
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked
    }
    private void spMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseExited
        // Change back to original color (usually white or light blue)
        jPanel3.setBackground(new java.awt.Color(240, 240, 240));         // TODO add your handling code here:
    }//GEN-LAST:event_spMouseExited

    private void spMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseEntered
        // Change to a light grey or your preferred hover color
        jPanel3.setBackground(new java.awt.Color(204, 204, 204));        // TODO add your handling code here:
    }//GEN-LAST:event_spMouseEntered

    private void spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseClicked
      staffprofile sp = new staffprofile();
    sp.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_spMouseClicked

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
      payments pay = new payments();
      pay.setVisible(true);
      this.dispose(); 
    }//GEN-LAST:event_payMouseClicked

    private void mbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbMouseClicked
        managebookings managebook = new managebookings();
        managebook.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardstaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardstaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardstaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardstaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardstaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel mb;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel sd;
    private javax.swing.JLabel sp;
    private javax.swing.JLabel welcome_staff;
    // End of variables declaration//GEN-END:variables
}
