/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardStaff;

import javax.swing.table.DefaultTableModel;
import config.session;
import config.config;
import java.sql.*;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.text.SimpleDateFormat;

public class editbooking extends javax.swing.JFrame {
    
    public String bookingID;

    /**
     * Creates new form editbooking
     */
    public editbooking() {
    initComponents();
    
    // Listen for changes in the Check-In date
    editcheckin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
        @Override
        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            if ("date".equals(evt.getPropertyName())) {
                calculateTotals();
            }
        }
    });

    // Listen for changes in the Check-Out date
    editcheckout.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
        @Override
        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            if ("date".equals(evt.getPropertyName())) {
                calculateTotals();
            }
        }
    });
}
    
    // Add listeners to calculate totals when dates change
    // Add these to editbooking.java
public void setCheckInDate(java.util.Date date) {
    editcheckin.setDate(date);
}

public void setCheckOutDate(java.util.Date date) {
    editcheckout.setDate(date);
}
    
    public void calculateTotals() {
    try {
        if (editcheckin.getDate() != null && editcheckout.getDate() != null) {
            // Convert java.util.Date to LocalDate for easier calculation
            LocalDate d1 = new java.sql.Date(editcheckin.getDate().getTime()).toLocalDate();
            LocalDate d2 = new java.sql.Date(editcheckout.getDate().getTime()).toLocalDate();

            // Calculate the difference in days
            long nights = ChronoUnit.DAYS.between(d1, d2);

            if (nights > 0) {
                editn.setText(String.valueOf(nights));
                
                // Assuming 500.00 is your per-night rate
                double rate = 500.00; 
                double total = nights * rate;
                
                edittc.setText(String.format("%.2f", total));
            } else {
                // If check-out is before or same as check-in
                editn.setText("0");
                edittc.setText("0.00");
            }
        }
    } catch (Exception e) {
        // Silently fail or log if dates are in middle of being updated
        System.out.println("Calc Error: " + e.getMessage());
    }
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        edittc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        editcheckin = new com.toedter.calendar.JDateChooser();
        editcheckout = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        updatebook = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editn = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        editar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(102, 204, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Total Cost:");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, 40));

        edittc.setEditable(false);
        jPanel9.add(edittc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, 40));

        jLabel12.setText("Check-Out:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 40));

        jLabel17.setText("Check-In:");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 40));
        jPanel9.add(editcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, 40));
        jPanel9.add(editcheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 40));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        jPanel11.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, 40));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatebook.setForeground(new java.awt.Color(255, 255, 255));
        updatebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatebook.setText("UPDATE BOOKING");
        updatebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebookMouseClicked(evt);
            }
        });
        jPanel12.add(updatebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, 40));

        jLabel2.setText("Available Rooms:");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 40));

        editn.setEditable(false);
        jPanel9.add(editn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 40));

        jLabel18.setText("Total Nights:");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 40));

        editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarMouseClicked(evt);
            }
        });
        jPanel9.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 270, 40));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 470, 381));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("EDIT BOOKING");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 110));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        dashboardstaff dash = new dashboardstaff();
        dash.setVisible(true); // Show the dashboard again
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void updatebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebookMouseClicked
    try {
        config db = new config();
        
        // Validation: Check if dates are selected
        if(editcheckin.getDate() == null || editcheckout.getDate() == null){
            JOptionPane.showMessageDialog(this, "Please select both Check-In and Check-Out dates.");
            return;
        }

        String room_type_name = editar.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String checkin = sdf.format(editcheckin.getDate());
        String checkout = sdf.format(editcheckout.getDate());
        
        // Use the public variable 'bookingID' that we defined above
        String sql = "UPDATE bookings SET room_id = ?, check_in = ?, check_out = ? WHERE bookings_id = ?";
        
        int result = db.executeUpdate(sql, room_type_name, checkin, checkout, bookingID);

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Booking updated successfully!");
            new managebookings().setVisible(true);
            this.dispose();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
    }
  
    }//GEN-LAST:event_updatebookMouseClicked

    private void editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarMouseClicked

    }//GEN-LAST:event_editarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editbooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancel;
    public javax.swing.JTextField editar;
    public com.toedter.calendar.JDateChooser editcheckin;
    public com.toedter.calendar.JDateChooser editcheckout;
    public javax.swing.JTextField editn;
    public javax.swing.JTextField edittc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel updatebook;
    // End of variables declaration//GEN-END:variables
}
