/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardStaff;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class payments extends javax.swing.JFrame {

    /**
     * Creates new form payments
     */
    public payments() {
        initComponents();
        displayPayments();
    }
    

public void displayPayments() {
    try {
        // Change the path to your actual database file location
        String url = "jdbc:sqlite:C:\\Users\\Administrator\\OneDrive\\Documents\\bryl\\brylbooking\\booking.db";
        Connection conn = DriverManager.getConnection(url);
        
        // Query to fetch all payment data
        String sql = "SELECT payment_id, bookings_id, amount, payment_method, payment_status, payment_date FROM payments";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        // Option A: If you have rs2xml.jar (DbUtils)
        paytable.setModel(DbUtils.resultSetToTableModel(rs));
        
        /* Option B: If you DON'T have DbUtils, use this loop instead:
        DefaultTableModel model = (DefaultTableModel) paytable.getModel();
        model.setRowCount(0); // Clear existing rows
        while(rs.next()){
            model.addRow(new Object[]{
                rs.getInt("payment_id"),
                rs.getInt("bookings_id"),
                rs.getDouble("amount"),
                rs.getString("payment_method"),
                rs.getString("payment_status"),
                rs.getString("payment_date")
            });
        }
        */
        
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error connecting to database: " + e.getMessage());
    }
}

private void showReceiptWindow(String paymentID) {
    try {
        Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\Users\\Administrator\\OneDrive\\Documents\\bryl\\brylbooking\\booking.db");
        // We join with bookings table to get more details if needed
        String sql = "SELECT * FROM payments WHERE payment_id = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, paymentID);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String receipt = "******************************************\n"
                           + "          BRYL HOTEL RECEIPT          \n"
                           + "******************************************\n"
                           + "Payment ID:  " + rs.getString("payment_id") + "\n"
                           + "Booking ID:  " + rs.getString("bookings_id") + "\n"
                           + "Method:      " + rs.getString("payment_method") + "\n"
                           + "Date:        " + rs.getString("payment_date") + "\n"
                           + "------------------------------------------\n"
                           + "TOTAL AMOUNT: PHP " + rs.getString("amount") + "\n"
                           + "STATUS:       " + rs.getString("payment_status") + "\n"
                           + "******************************************\n"
                           + "       Thank you for your stay!       ";

            // Create a simple text area to show the receipt
            javax.swing.JTextArea textArea = new javax.swing.JTextArea(receipt);
            textArea.setEditable(false);
            textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
            
            JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(textArea), "Digital Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error generating receipt: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
